### PR TITLE
Stry 4 issue 55 integration

### PR DESCRIPTION
**Pull request by s1hu**
Integrated Signup and Signin functionality in react client using hooks and context. 

To setup the project's client proxy and the backend database, see following document made by Sanjana:
https://docs.google.com/document/d/1IW0Ix4RWG8byFd8QsnMmmN8UWCFl5WnvbT8Shei0Fhs/edit?usp=sharing

### CODE REVIEW

**Review by s1hu — COMMENTED** [review]
Sometimes test cannot pass and will say that some modules are missing. This might be due to file renaming/refactoring issues. If the content of a file has not changed, git will not detect and push such changes. In my case the file name is changed so that it begins with a capitalized letter. If that is the case, clear the git local cache and re-add all the changes. 

`git rm -r --cached . && git add --all . `

**Review by Rebooting-Me — COMMENTED** [review]
So the warnings are gone now?

**Comment by s1hu** [comment]
> So the warnings are gone now?

Yep. I removed the `concurrently` setting since it was accidently put into the Jest setup, also `npm` doesn't seem to need it currently.

**Review by and-le — APPROVED** [review]
Looks good to me.

**Comment by and-le** [comment]
@s1hu Please list which tasks this closes as well.

**Pull request merged**
